# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.project.year
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI ?? => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha      # alpha: ??? ? ?? ??, method: HTTP Method ? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

# DB ??
server:
  servlet:
    encoding:
      force-response: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: localhost
    username: root
    password: dlehdduq798!